version: "2"
services:
  mongo3:
    container_name: mongo3
    image: mongo:3.4
    mem_limit: 128m
    ports:
      - "27018:27018"
      - "28018:28018"
    networks:
      - my-net
    restart: always
    volumes:
      - ./data/rs0-3:/data/db
    entrypoint: [ "mongod", "--replSet", "rs0", "--nojournal", "--smallfiles", "--rest", "--noprealloc", "--port", "27018" ]
  mongo2:
    container_name: mongo2
    image: mongo:3.4
    mem_limit: 256m
    ports:
      - "27019:27019"
      - "28019:28019"
    networks:
      - my-net
    restart: always
    volumes:
      - ./data/rs0-2:/data/db
    entrypoint: [ "mongod", "--replSet", "rs0", "--journal", "--smallfiles", "--rest", "--port", "27019" ]
  mongo1:
    container_name: mongo1
    image: mongo:3.4
    mem_limit: 256m
    ports:
      - "27017:27017"
      - "28017:28017"
    networks:
      - my-net
    restart: always
    volumes:
      - ./data/rs0-1:/data/db
    entrypoint: [ "mongod", "--replSet", "rs0", "--journal", "--smallfiles", "--rest", "--port", "27017" ]
  # Configures the MongoDB replicaset
  mongosetup:
    image: mongo:3.4
    mem_limit: 128m
    networks:
      - my-net
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ]
  # Parse-server
  parseapi:
    container_name: parseapi
    mem_limit: 256m
    build: ./parse-server
    networks:
      - my-net
    ports:
      - "1337:1337"
    restart: always
    volumes:
      - ./parse-server/cloud:/parse/cloud
      - ./parse-server/public:/parse/public
networks:
  my-net:
    driver: bridge
