version: "2"
services:
  mongo3:
    container_name: mongo3
    image: mongo:3.4
    mem_limit: 64m
    ports:
      - "27018:27018"
      - "28018:28018"
    networks:
      - my-net
    restart: always
    volumes:
      - ./data/rs03:/data/db
      - ./keyfile:/srv/mongodb
    entrypoint: [ "mongod", "--replSet", "rs0", "--nojournal", "--smallfiles", "--rest", "--noprealloc", "--port", "27018", "--auth", "--keyFile", "/srv/mongodb/mongodb-keyfile" ]
  mongo2:
    container_name: mongo2
    image: mongo:3.4
    mem_limit: 128m
    ports:
      - "27019:27019"
      - "28019:28019"
    networks:
      - my-net
    restart: always
    volumes:
      - ./data/rs02:/data/db
      - ./keyfile:/srv/mongodb
    entrypoint: [ "mongod", "--replSet", "rs0", "--journal", "--smallfiles", "--rest", "--port", "27019", "--auth", "--keyFile", "/srv/mongodb/mongodb-keyfile" ]
  mongo1:
    container_name: mongo1
    image: mongo:3.4
    mem_limit: 128m
    ports:
      - "27017:27017"
      - "28017:28017"
    networks:
      - my-net
    restart: always
    volumes:
      - ./data/rs01:/data/db
      - ./keyfile:/srv/mongodb
    entrypoint: [ "mongod", "--replSet", "rs0", "--journal", "--smallfiles", "--rest", "--port", "27017", "--auth", "--keyFile", "/srv/mongodb/mongodb-keyfile" ]
  # Configures the MongoDB replicaset
  mongosetup:
    mem_limit: 64m
    build: ./mongosetup
    networks:
      - my-net
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/srv/mongodb
    entrypoint: [ "/scripts/setup.sh" ]
  # Parse-server
  parseapi:
    container_name: parseapi
    mem_limit: 128m
    build: ./parse-server
    networks:
      - my-net
    restart: always
    volumes:
      - ./parse-server/cloud:/parse/cloud
      - ./parse-server/public:/parse/public
  # nginx proxy
  nginx:
    container_name: nginx
    mem_limit: 32m
    build: ./nginx/
    depends_on:
      - parseapi
    networks:
      - my-net
    ports:
      - "80:80"
    restart: always
networks:
  my-net:
    driver: bridge
